  # Step 2: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/projek-akhir", "."]
    dir: "be"

  # Step 3: Push image ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/projek-akhir"]

  # Step 4: Deploy ke Cloud Run menggunakan env.yaml
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "projek-akhir",
        "--image",
        "gcr.io/$PROJECT_ID/projek-akhir",
        "--timeout",
        "360s",
        "--port",
        "5001",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
